---
- name: Start docker container
  delegate_to: localhost
  docker_container:
    name: "{{ container_name }}"
    image: "{{ image_name }}"
    volumes:
      - "{{ local_build_dir }}:{{ build_dir }}"
    env:
      SSH_AUTH_SOCK: /ssh-agent
    auto_remove: yes
    detach: yes
    interactive: yes
    tty: yes